.travis.yml, MANIFEST, MANIFEST.SKIP, README.md
Only runs distcheck
Includes build badge in README
Closes #4
=> Add travis configuration

.travis.yml
Add a step in Travis to test package creation
=> Have travis test package building

.travis.yml
See
https://github.com/linz/bde-processor-deployment/issues/23#issuecomment-307760791
=> Use Ubuntu 14.04 (trusty) for travis testing

.travis.yml, MANIFEST.SKIP
See https://github.com/linz/bde-processor-deployment/issues/23
=> Add travis building for release-1.0 branch

t/BdeDataset.t, t/BdeFile.t, t/BdeRepository.t, t/data/pab1.crs
=> Add test for Bde modules

.travis.yml
As it is available in Travis...
=> Also test with Perl 5.26

lib/LINZ/Bde.pm
And add a check for writeability on it
=> Also accept character device for /dev/stdout use

.travis.yml
may make bad assumptions
See #32
=> [travis] omit language specification

configure
NOTE: this is a very crude approach, but doing it in a clean
way is so complex that discouraged me :)
=> Add a "deb" rule to the generated Makefile

lib/LINZ/Bde.pm
Give detail about unusable /dev/stdout
=> Improve /dev/stdout handling

NEWS.md, lib/LINZ/Bde.pm, t/BdeFile.t
Closes #19
Enables a test for it
=> Fix typo in BdeFile::archive_files

NEWS.md, lib/LINZ/Bde.pm
=> Make sure bde_copy exit code is taken in consideration by "copy"

Build.PL, NEWS.md
=> Set version and release date for 1.1.0

Build.PL, NEWS.md
=> Target 1.2.0 release

lib/LINZ/Bde.pm
otherwise it keeps popping up during upload of multiple tables...
=> Remove debugging line

.travis.yml, lib/LINZ/Bde.pm
=> [travis] Use Bionic distribution

.travis.yml, Build.PL, NEWS.md, lib/LINZ/Bde.pm
Emerges upon creating bionic packages (#47)
=> Fix "Experimental push on scalar now forbidden" perl 5.26 error on `make check`

NEWS.md, lib/LINZ/Bde.pm
To reduce lots of temporary files left on the system
=> Prefix and auto-cleanup temporary files

Build.PL
As Travis occasionally still fails :(
See https://travis-ci.org/linz/linz-bde-perl/builds/583559303
=> [travis] Manually install perl Module::Signature

.github/workflows/test.yml, README.md
=> Github test action and badge

.github/workflows/test.yml
Otherwise pushes to master are not being tested..
=> [ga] Have github-actions also trigger on pushes to stable branches

.github/dependabot.yml, .gitignore
=> feat: Configure Dependabot for GitHub Actions

.kodiak.toml
=> feat: Configure Kodiak

.github/workflows/test.yml
=> tests: Build on Ubuntu LTS

.github/workflows/test.yml
See change log
<https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.17.0>.
=> fix: Use action supporting Ubuntu 18

.github/workflows/test.yml, bump-nix.bash, nixpkgs.json, shell.nix
=> build: Ubuntu 22.04
